//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.03 at 09:15:32 AM AEST 
//


package au.net.electronichealth.ns.cda._2_0;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AddressLine.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="AddressLine">
 *   &lt;restriction base="{urn:hl7-org:v3}cs">
 *     &lt;enumeration value="ADL"/>
 *     &lt;enumeration value="AL"/>
 *     &lt;enumeration value="BNN"/>
 *     &lt;enumeration value="BNR"/>
 *     &lt;enumeration value="BNS"/>
 *     &lt;enumeration value="DAL"/>
 *     &lt;enumeration value="DINST"/>
 *     &lt;enumeration value="DINSTA"/>
 *     &lt;enumeration value="DINSTQ"/>
 *     &lt;enumeration value="DIR"/>
 *     &lt;enumeration value="DMOD"/>
 *     &lt;enumeration value="DMODID"/>
 *     &lt;enumeration value="INT"/>
 *     &lt;enumeration value="POB"/>
 *     &lt;enumeration value="SAL"/>
 *     &lt;enumeration value="STB"/>
 *     &lt;enumeration value="STR"/>
 *     &lt;enumeration value="STTYP"/>
 *     &lt;enumeration value="UNID"/>
 *     &lt;enumeration value="UNIT"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "AddressLine")
@XmlEnum
public enum AddressLine {

    ADL,
    AL,
    BNN,
    BNR,
    BNS,
    DAL,
    DINST,
    DINSTA,
    DINSTQ,
    DIR,
    DMOD,
    DMODID,
    INT,
    POB,
    SAL,
    STB,
    STR,
    STTYP,
    UNID,
    UNIT;

    public String value() {
        return name();
    }

    public static AddressLine fromValue(String v) {
        return valueOf(v);
    }

}
