//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.03 at 09:15:32 AM AEST 
//


package au.net.electronichealth.ns.cda._2_0;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EntityClass.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="EntityClass">
 *   &lt;restriction base="{urn:hl7-org:v3}cs">
 *     &lt;enumeration value="ANM"/>
 *     &lt;enumeration value="CER"/>
 *     &lt;enumeration value="CHEM"/>
 *     &lt;enumeration value="CITY"/>
 *     &lt;enumeration value="CONT"/>
 *     &lt;enumeration value="COUNTRY"/>
 *     &lt;enumeration value="COUNTY"/>
 *     &lt;enumeration value="DEV"/>
 *     &lt;enumeration value="ENT"/>
 *     &lt;enumeration value="FOOD"/>
 *     &lt;enumeration value="HCE"/>
 *     &lt;enumeration value="HOLD"/>
 *     &lt;enumeration value="LIV"/>
 *     &lt;enumeration value="MAT"/>
 *     &lt;enumeration value="MIC"/>
 *     &lt;enumeration value="MMAT"/>
 *     &lt;enumeration value="MODDV"/>
 *     &lt;enumeration value="NAT"/>
 *     &lt;enumeration value="NLIV"/>
 *     &lt;enumeration value="ORG"/>
 *     &lt;enumeration value="PLC"/>
 *     &lt;enumeration value="PLNT"/>
 *     &lt;enumeration value="PROVINCE"/>
 *     &lt;enumeration value="PSN"/>
 *     &lt;enumeration value="PUB"/>
 *     &lt;enumeration value="RGRP"/>
 *     &lt;enumeration value="STATE"/>
 *     &lt;enumeration value="EMP"/>
 *     &lt;enumeration value="IDENT"/>
 *     &lt;enumeration value="QUAL"/>
 *     &lt;enumeration value="COV"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "EntityClass")
@XmlEnum
public enum EntityClass {

    ANM,
    CER,
    CHEM,
    CITY,
    CONT,
    COUNTRY,
    COUNTY,
    DEV,
    ENT,
    FOOD,
    HCE,
    HOLD,
    LIV,
    MAT,
    MIC,
    MMAT,
    MODDV,
    NAT,
    NLIV,
    ORG,
    PLC,
    PLNT,
    PROVINCE,
    PSN,
    PUB,
    RGRP,
    STATE,
    EMP,
    IDENT,
    QUAL,
    COV;

    public String value() {
        return name();
    }

    public static EntityClass fromValue(String v) {
        return valueOf(v);
    }

}
