//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.03 at 09:15:32 AM AEST 
//


package au.net.electronichealth.ns.cda._2_0;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EntityNameUse.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="EntityNameUse">
 *   &lt;restriction base="{urn:hl7-org:v3}cs">
 *     &lt;enumeration value="ABC"/>
 *     &lt;enumeration value="C"/>
 *     &lt;enumeration value="IDE"/>
 *     &lt;enumeration value="L"/>
 *     &lt;enumeration value="OR"/>
 *     &lt;enumeration value="SYL"/>
 *     &lt;enumeration value="A"/>
 *     &lt;enumeration value="I"/>
 *     &lt;enumeration value="P"/>
 *     &lt;enumeration value="R"/>
 *     &lt;enumeration value="PHON"/>
 *     &lt;enumeration value="SRCH"/>
 *     &lt;enumeration value="SNDX"/>
 *     &lt;enumeration value="T"/>
 *     &lt;enumeration value="DN"/>
 *     &lt;enumeration value="M"/>
 *     &lt;enumeration value="NB"/>
 *     &lt;enumeration value="UI"/>
 *     &lt;enumeration value="SP"/>
 *     &lt;enumeration value="ORGU"/>
 *     &lt;enumeration value="ORGS"/>
 *     &lt;enumeration value="ORGB"/>
 *     &lt;enumeration value="ORGL"/>
 *     &lt;enumeration value="ORGA"/>
 *     &lt;enumeration value="ORGE"/>
 *     &lt;enumeration value="ORGX"/>
 *     &lt;enumeration value="ORGY"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "EntityNameUse")
@XmlEnum
public enum EntityNameUse {

    ABC,
    C,
    IDE,
    L,
    OR,
    SYL,
    A,
    I,
    P,
    R,
    PHON,
    SRCH,
    SNDX,
    T,
    DN,
    M,
    NB,
    UI,
    SP,
    ORGU,
    ORGS,
    ORGB,
    ORGL,
    ORGA,
    ORGE,
    ORGX,
    ORGY;

    public String value() {
        return name();
    }

    public static EntityNameUse fromValue(String v) {
        return valueOf(v);
    }

}
