//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.03 at 09:15:32 AM AEST 
//


package au.net.electronichealth.ns.cda._2_0;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RoleClassPartitive.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="RoleClassPartitive">
 *   &lt;restriction base="{urn:hl7-org:v3}cs">
 *     &lt;enumeration value="ACTI"/>
 *     &lt;enumeration value="ACTIB"/>
 *     &lt;enumeration value="ACTIM"/>
 *     &lt;enumeration value="ACTIR"/>
 *     &lt;enumeration value="ACTM"/>
 *     &lt;enumeration value="ADTV"/>
 *     &lt;enumeration value="ALQT"/>
 *     &lt;enumeration value="BASE"/>
 *     &lt;enumeration value="COLR"/>
 *     &lt;enumeration value="CONT"/>
 *     &lt;enumeration value="EXPAGTCAR"/>
 *     &lt;enumeration value="EXPVECTOR"/>
 *     &lt;enumeration value="FLVR"/>
 *     &lt;enumeration value="FOMITE"/>
 *     &lt;enumeration value="IACT"/>
 *     &lt;enumeration value="INGR"/>
 *     &lt;enumeration value="ISLT"/>
 *     &lt;enumeration value="LOCE"/>
 *     &lt;enumeration value="MBR"/>
 *     &lt;enumeration value="PART"/>
 *     &lt;enumeration value="PRSV"/>
 *     &lt;enumeration value="SPEC"/>
 *     &lt;enumeration value="STBL"/>
 *     &lt;enumeration value="STOR"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "RoleClassPartitive")
@XmlEnum
public enum RoleClassPartitive {

    ACTI,
    ACTIB,
    ACTIM,
    ACTIR,
    ACTM,
    ADTV,
    ALQT,
    BASE,
    COLR,
    CONT,
    EXPAGTCAR,
    EXPVECTOR,
    FLVR,
    FOMITE,
    IACT,
    INGR,
    ISLT,
    LOCE,
    MBR,
    PART,
    PRSV,
    SPEC,
    STBL,
    STOR;

    public String value() {
        return name();
    }

    public static RoleClassPartitive fromValue(String v) {
        return valueOf(v);
    }

}
