//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.03 at 09:15:32 AM AEST 
//


package au.net.electronichealth.ns.ci.cda.extensions._3;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import au.net.electronichealth.ns.cda._2_0.ParticipationType;


/**
 * <p>Java class for Participant complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Participant">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="participantRole" type="{http://ns.electronichealth.net.au/Ci/Cda/Extensions/3.0}ParticipantRole"/>
 *       &lt;/sequence>
 *       &lt;attribute name="typeCode" type="{urn:hl7-org:v3}ParticipationType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Participant", propOrder = {
    "participantRole"
})
public class Participant {

    @XmlElement(required = true)
    protected ParticipantRole participantRole;
    @XmlAttribute(name = "typeCode")
    protected ParticipationType typeCode;

    /**
     * Gets the value of the participantRole property.
     * 
     * @return
     *     possible object is
     *     {@link ParticipantRole }
     *     
     */
    public ParticipantRole getParticipantRole() {
        return participantRole;
    }

    /**
     * Sets the value of the participantRole property.
     * 
     * @param value
     *     allowed object is
     *     {@link ParticipantRole }
     *     
     */
    public void setParticipantRole(ParticipantRole value) {
        this.participantRole = value;
    }

    /**
     * Gets the value of the typeCode property.
     * 
     * @return
     *     possible object is
     *     {@link ParticipationType }
     *     
     */
    public ParticipationType getTypeCode() {
        return typeCode;
    }

    /**
     * Sets the value of the typeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link ParticipationType }
     *     
     */
    public void setTypeCode(ParticipationType value) {
        this.typeCode = value;
    }

}
